---

- name: update the nginx.conf
  become: yes
  copy:
    src: nginx.conf
    dest: "{{ dir_openresty }}"

- name: ensure conf.d dir exists
  become: yes
  file:
    path: "{{ dir_openresty_conf }}"
    state: directory
    owner: root
    mode: "0755"

- name: update the index.nginx
  become: yes
  template:
    src: index.nginx
    dest: "{{ dir_openresty_conf }}"

- name: test config syntax
  become: yes
  command: openresty -t
  register: result_test

- name: reload openresty
  become: yes
  command: openresty -s reload
  when: result_test.rc is defined and result_test.rc == 0

  