---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kisho-mysql
  namespace: kisho-cinema
  labels:
    app: kisho-mysql
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kisho-mysql
  template:
    metadata:
      labels:
        app: kisho-mysql
    spec:
      nodeSelector:
        role: worker
      volumes:
        - name: mysql-volume
      containers:
        - name: kisho-mysql
          image: jazzplato/kisho-demo-cinema-mysql:1.0
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-volume
              mountPath: /var/lib/mysql
