---
kind: Service
apiVersion: v1
metadata:
  name: service-mysql
  namespace: kisho-cinema
  labels:
    app: kisho-mysql
spec:
  type: NodePort
  selector:
    app: kisho-mysql
  ports:
  - protocol: TCP
    port: 3306
    nodePort: {{ port_mysql | int }}
  externalTrafficPolicy: Local