---
- name: deploy prometheus
  hosts: k8s_master
  vars:
    dir_deployment: "{{ inventory_dir }}"
    dir_k8s: "{{ dir_deployment }}/kubernetes"
    dir_k8s_prometheus: "{{ dir_k8s }}/monitoring/prometheus"
  pre_tasks:
    - name: ensure k8s module dependencies are installed.
      pip:
        state: present
        name: openshift
  roles:
    - create_namespaces
    - deploy_prometheus
