---
- name: deploy kisho cinema
  hosts: k8s_master
  become: yes
  become_user: "{{ k8s_user }}"
  vars:
    dir_deployment: "{{ inventory_dir }}"
    dir_k8s: "{{ dir_deployment }}/kubernetes"
    dir_k8s_kisho: "{{ dir_k8s }}/kisho-cinema"
    django_enable_cache: no
  pre_tasks:
    - name: ensure k8s module dependencies are installed.
      pip:
        name: openshift
        state: present
  roles:
    - create_namespaces
    - deploy_mysql
    # - deploy_redis
    - deploy_django
    - deploy_nginx
