---

- name: update proxy
  hosts: "{{ env }}"
  vars:
    hostname: "{{ inventory_hostname }}"
    dir_openresty: /etc/openresty
    dir_openresty_conf: "{{ dir_openresty }}/conf.d"
  roles:
    - config_openresty