---
- name: deploy prometheus to k8s cluster
  include_role:
    name: deploy_k8s
  vars:
    dir_config: "{{ dir_k8s_prometheus }}"
    files:
      - cluster-role.yml
      - cluster-role-binding.yml
      - config-map.yml
      - deployment.yml
      - service.yml
