---
kind: Service
apiVersion: v1
metadata:
  name: service-nginx
  namespace: kisho-cinema
  labels:
    app: kisho-nginx
spec:
  type: NodePort
  selector:
    app: kisho-nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: {{ port_nginx | int }}
  externalTrafficPolicy: Local
