---

kind: Service
apiVersion: v1
metadata:
  name: service-django
  namespace: kisho-cinema
  labels:
    app: kisho-django
spec:
  type: NodePort
  selector:
    app: kisho-django
  ports:
    - protocol: TCP
      port: 8080
      nodePort: 30001
  externalTrafficPolicy: Local
